added better query

diff --git a/scripts/query b/scripts/query
--- a/scripts/query
+++ b/scripts/query
@@ -1,8 +1,27 @@
 #!/usr/bin/env bash
 
-if [[ ! -S "$NVIM_SOCKET" ]]; then
-  nvim --listen "$NVIM_SOCKET" -c "lua require('odas0r.zet').search(\"${1}\",{${2}})"
-else
-  nvim --server "$NVIM_SOCKET" --remote-send "<C-\><C-N>:wincmd p | lua terminal:close()<CR>"
-  nvim --server "$NVIM_SOCKET" --remote-send "<C-\><C-N>:wincmd p | lua require('odas0r.zet').search(\"${1}\",{${2}})<CR>i"
+INITIAL_QUERY="${1:-}"
+FLEET_PATH="$2"
+PERM_PATH="$3"
+
+if [[ -z $FLEET_PATH ]] || [[ -z "$PERM_PATH" ]]; then
+  echo "error: invalid args on script 'query'"
+  exit 1
 fi
+
+RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
+IFS=: read -ra selected < <(
+  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf '%q %q %q' "$INITIAL_QUERY" "$FLEET_PATH" "$PERM_PATH")" \
+    fzf-tmux -p 95% --ansi \
+    --color "hl:-1:underline,hl+:-1:underline:reverse" \
+    --disabled --query "$INITIAL_QUERY" \
+    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} $FLEET_PATH $PERM_PATH || true" \
+    --bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(2. fzf> )+enable-search+clear-query+rebind(ctrl-r)" \
+    --bind "ctrl-r:unbind(ctrl-r)+change-prompt(1. ripgrep> )+disable-search+reload($RG_PREFIX {q} $FLEET_PATH $PERM_PATH || true)+rebind(change,ctrl-f)" \
+    --prompt '1. Ripgrep> ' \
+    --delimiter : \
+    --header '╱ CTRL-R (Ripgrep mode) ╱ CTRL-F (fzf mode) ╱' \
+    --preview 'batcat --theme=gruvbox-dark --color=always {1} --highlight-line {2}' \
+)
+
+echo "${selected[1]}:${selected[0]}"
